default: both

both:
	gcc  -Wall -o random random.c
	gcc  -Wall -o urandom urandom.c
random:
	gcc  -Wall -o random random.c
urandom:
	gcc  -Wall -o urandom urandom.c

clean:
	-rm -f random
	-rm -f urandom
